[toolchain]
anchor_version = "1.0.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rektofun_program = "4i89kL32hf4AzZwgqboFEVgJxAgVXxpDkyrGeJRnZtHT"

[programs.mainnet]
rektofun_program = "4i89kL32hf4AzZwgqboFEVgJxAgVXxpDkyrGeJRnZtHT"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/rekto-deploy.json"

[scripts]
test = "cargo test"

[hooks]
